import Voucher from "../models/Voucher";
import axios from "axios";

// We reuse the basic config from environment variables (assuming same .env source)
const PROHANDEL_CONFIG = {
    authUrl: process.env.PROHANDEL_AUTH_URL || 'https://auth.prohandel.cloud/api/v4',
    apiUrl: process.env.PROHANDEL_API_URL || 'https://linde.prohandel.de/api/v2',
    apiKey: process.env.PROHANDEL_API_KEY,
    apiSecret: process.env.PROHANDEL_API_SECRET
};

/**
 * Authentication and API helper for Pro Handel
 * (Ideally these should be a shared library, but we inline for Microservice separation)
 */
async function getProHandelHeaders() {
    try {
        const authData = { apiKey: PROHANDEL_CONFIG.apiKey, secret: PROHANDEL_CONFIG.apiSecret };
        const authRes = await axios.post(`${PROHANDEL_CONFIG.authUrl}/token`, authData, { timeout: 10000 });
        const token = authRes.data.token.token.value;
        return {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
        };
    } catch (err) {
        console.error('❌ ProHandel Auth Failed:', err.message);
        throw err;
    }
}

/**
 * Create a Voucher in Pro Handel system
 * This returns the integer 'number' (Code) and UUID 'id'.
 */
async function createProHandelVoucher(amount, orderRef) {
    const headers = await getProHandelHeaders();

    // Per documentation: POST /api/v2/voucher
    const payload = {
        branchNumber: 1, // Default online branch?
        value: amount,
        note: `Online Order: ${orderRef}`
        // 'number' is autogenerated by Pro Handel
    };

    console.log(`📡 Creating ProHandel voucher for ${amount} EUR...`);
    const response = await axios.post(`${PROHANDEL_CONFIG.apiUrl}/voucher`, payload, { headers });

    if (response.status === 201 || response.status === 200) {
        return response.data; // Should contain { id, number, value, internetCode... }
    }
    throw new Error(`ProHandel API returned status ${response.status}`);
}


/**
 * Core Logic: Handle incoming Shopify Order
 */
export async function processOrder(order) {
    if (!order.line_items) return;

    // Filter for Voucher items
    // Logic: SKU starts with 'GUTSCHEIN' or Product Type is 'Gift Card'
    // Note: If Shopify handles Gift Cards natively (digital), the item name might differ.
    const voucherItems = order.line_items.filter(item =>
        (item.sku && item.sku.toUpperCase().startsWith('GUTSCHEIN')) ||
        (item.name && item.name.toLowerCase().includes('gutschein')) ||
        item.gift_card === true
    );

    if (voucherItems.length === 0) return;

    console.log(`🎟 Found ${voucherItems.length} voucher items in Order ${order.name}`);

    for (const item of voucherItems) {
        // Idempotency: Check if we already created a voucher for this line item
        const existing = await Voucher.findOne({
            shopifyOrderId: order.id.toString(),
            'metadata.lineItemId': item.id.toString()
        });

        if (existing) {
            console.log(`⚠️ Voucher for item ${item.id} already exists. Skipping.`);
            continue;
        }

        const amount = parseFloat(item.price);
        if (isNaN(amount) || amount <= 0) {
            console.warn(`⚠️ Invalid amount for voucher item ${item.title}`);
            continue;
        }

        try {
            // 1. Create in Pro Handel (The Master Record)
            const phVoucher = await createProHandelVoucher(amount, order.name);

            const phNumber = phVoucher.number; // e.g. 105021
            const phUuid = phVoucher.id;

            console.log(`✅ Created ProHandel Voucher #${phNumber} (${phUuid})`);

            // 2. Sync logic (Create mapped record in our DB)
            // The 'shopifyCode' is key. We DECIDE to use the Pro Handel Number as the code.
            // If Shopify generated a code (native Gift Card), we might have to store that instead.
            // BUT for "normal product as voucher" flow, we define the code.

            // Attempt to Create matching Shopify Gift Card (If API scope allows) - NOT IMPLEMENTED HERE
            // For now, we assume we just send the code to the customer.

            const newVoucher = new Voucher({
                shopifyCode: phNumber.toString(), // UNIFIED NUMBER STRATEGY
                shopifyOrderId: order.id.toString(),
                proHandelNumber: phNumber,
                proHandelUuid: phUuid,
                value: amount,
                initialValue: amount,
                status: 'active',
                issuedAt: new Date(),
                metadata: {
                    lineItemId: item.id.toString(),
                    customerEmail: order.email,
                    productName: item.name
                },
                customer: {
                    shopifyId: order.customer?.id?.toString(),
                    email: order.email || order.customer?.email,
                    firstName: order.customer?.first_name,
                    lastName: order.customer?.last_name
                }
            });

            await newVoucher.save();
            console.log(`💾 Saved Voucher Mapping: PH #${phNumber} <-> Shopify Order ${order.name}`);

            // TODO: Send Email with Code `phNumber` to `order.email`
            // await sendVoucherEmail(order.email, phNumber, amount);

        } catch (err) {
            console.error(`❌ Failed to process voucher for item ${item.title}:`, err.message);
            // TODO: Add to retry queue
        }
    }
}
