import Voucher from "../models/Voucher";
import axios from "axios";

// We reuse the basic config from environment variables (assuming same .env source)
const PROHANDEL_CONFIG = {
    authUrl: process.env.PROHANDEL_AUTH_URL || 'https://auth.prohandel.cloud/api/v4',
    apiUrl: process.env.PROHANDEL_API_URL || 'https://linde.prohandel.de/api/v2',
    apiKey: process.env.PROHANDEL_API_KEY,
    apiSecret: process.env.PROHANDEL_API_SECRET
};

/**
 * Authentication and API helper for Pro Handel
 * (Ideally these should be a shared library, but we inline for Microservice separation)
 */
async function getProHandelHeaders() {
    try {
        const authData = { apiKey: PROHANDEL_CONFIG.apiKey, secret: PROHANDEL_CONFIG.apiSecret };
        const authRes = await axios.post(`${PROHANDEL_CONFIG.authUrl}/token`, authData, { timeout: 10000 });
        const token = authRes.data.token.token.value;
        return {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
        };
    } catch (err) {
        console.error('❌ ProHandel Auth Failed:', err.message);
        throw err;
    }
}

/**
 * Create a Voucher in Pro Handel system
 * This returns the integer 'number' (Code) and UUID 'id'.
 */
async function createProHandelVoucher(amount, orderRef) {
    const headers = await getProHandelHeaders();

    // Per documentation: POST /api/v2/voucher
    const payload = {
        branchNumber: 1, // Default online branch?
        value: amount,
        note: `Online Order: ${orderRef}`
        // 'number' is autogenerated by Pro Handel
    };

    console.log(`📡 Creating ProHandel voucher for ${amount} EUR...`);
    const response = await axios.post(`${PROHANDEL_CONFIG.apiUrl}/voucher`, payload, { headers });

    if (response.status === 201 || response.status === 200) {
        return response.data; // Should contain { id, number, value, internetCode... }
    }
    throw new Error(`ProHandel API returned status ${response.status}`);
}


/**
 * Core Logic: Handle incoming Shopify Order
 */
export async function processOrder(order, admin) {
    if (!order.line_items) return;

    // Filter for Voucher items
    const voucherItems = order.line_items.filter(item =>
        (item.sku && item.sku.toUpperCase().startsWith('GUTSCHEIN')) ||
        (item.name && item.name.toLowerCase().includes('gutschein')) ||
        item.gift_card === true
    );

    if (voucherItems.length === 0) return;

    console.log(`🎟 Found ${voucherItems.length} voucher items in Order ${order.name}`);

    for (const item of voucherItems) {
        // Idempotency check
        const existing = await Voucher.findOne({
            shopifyOrderId: order.id.toString(),
            'metadata.lineItemId': item.id.toString()
        });

        if (existing) {
            console.log(`⚠️ Voucher for item ${item.id} already exists. Skipping.`);
            continue;
        }

        const amount = parseFloat(item.price);
        if (isNaN(amount) || amount <= 0) continue;

        try {
            // 1. Create in Pro Handel
            const phVoucher = await createProHandelVoucher(amount, order.name);

            const phNumber = phVoucher.number;
            const phUuid = phVoucher.id;
            const phInternetCode = phVoucher.internetCode;

            console.log(`✅ Created ProHandel Voucher #${phNumber} (${phUuid}) Code: ${phInternetCode}`);

            // UNIFIED FORMAT: Use internetCode if valid, otherwise number
            const unifiedCode = phInternetCode && phInternetCode.length > 3 ? phInternetCode : phNumber.toString();

            // 2. Create Native Shopify Gift Card (if admin context available)
            let shopifyGiftCardId = null;
            if (admin) {
                try {
                    const giftCard = new admin.rest.resources.GiftCard({ session: admin.session });
                    giftCard.code = unifiedCode;
                    giftCard.initial_value = amount;
                    giftCard.note = `ProHandel Sync: ${phNumber}`;
                    await giftCard.save({ update: true });
                    shopifyGiftCardId = giftCard.id;
                    console.log(`✅ Created Native Shopify Gift Card ID: ${shopifyGiftCardId}`);
                } catch (gcErr) {
                    console.error("⚠️ Failed to create Shopify Gift Card:", gcErr.message);
                    // Continue to save DB record anyway
                }
            }

            const newVoucher = new Voucher({
                shopifyCode: unifiedCode,
                shopifyOrderId: order.id.toString(),
                shopifyGiftCardId: shopifyGiftCardId ? shopifyGiftCardId.toString() : undefined,
                proHandelNumber: phNumber,
                proHandelUuid: phUuid,
                value: amount,
                initialValue: amount,
                status: 'active',
                issuedAt: new Date(),
                metadata: {
                    lineItemId: item.id.toString(),
                    customerEmail: order.email,
                    productName: item.name
                },
                customer: {
                    shopifyId: order.customer?.id?.toString(),
                    email: order.email || order.customer?.email,
                    firstName: order.customer?.first_name,
                    lastName: order.customer?.last_name
                }
            });

            await newVoucher.save();
            console.log(`💾 Saved Voucher Mapping: PH #${phNumber} <-> Shopify Order ${order.name}`);

        } catch (err) {
            console.error(`❌ Failed to process voucher for item ${item.title}:`, err.message);
        }
    }
}

/**
 * Redeem a Voucher in Pro Handel system
 */
async function redeemProHandelVoucher(voucherUuid, amount, orderName) {
    const headers = await getProHandelHeaders();

    // POST /api/v2/voucher/redeem/{voucherId}
    const payload = {
        branchNumber: 1, // Default online branch
        amount: amount,
        note: `Redeemed in Shopify Order: ${orderName}`
        // Optional: customerNumber, etc.
    };

    console.log(`💸 Redeeming ProHandel Voucher ${voucherUuid} for ${amount} EUR...`);
    try {
        const response = await axios.post(`${PROHANDEL_CONFIG.apiUrl}/voucher/redeem/${voucherUuid}`, payload, { headers });
        return response.data;
    } catch (err) {
        console.error(`❌ ProHandel Redemption Failed: ${err.message}`);
        // If 400, maybe already redeemed?
        if (err.response) console.error(err.response.data);
        throw err;
    }
}

/**
 * Handle Gift Card Usage (Redemption) in Shopify
 */
export async function processRedemptions(order, admin) {
    // 1. Check if Gift Card was used
    const paymentGateways = order.payment_gateway_names || [];
    if (!paymentGateways.includes('gift_card')) return;

    if (!admin) {
        console.error("⚠️ Cannot process redemptions without Admin context to fetch transactions.");
        return;
    }

    console.log(`📉 Processing Redemptions for Order ${order.name}`);

    try {
        // 2. Fetch Transactions to identify the Gift Card
        // We need transactions to get the gift_card_id
        const transactions = await admin.rest.resources.Transaction.all({
            order_id: order.id,
            session: admin.session
        });

        for (const tx of transactions.data) {
            if (tx.gateway === 'gift_card' && tx.status === 'success' && tx.receipt && tx.receipt.gift_card_id) {
                const shopifyGiftCardId = tx.receipt.gift_card_id.toString();
                const amount = parseFloat(tx.amount);

                // 3. Find Linked Voucher
                const voucher = await Voucher.findOne({ shopifyGiftCardId: shopifyGiftCardId });

                if (voucher) {
                    // 4. Redeem in ProHandel
                    // Idempotency: Link this redemption to this order? 
                    // ProHandel allows partial redemptions.

                    try {
                        await redeemProHandelVoucher(voucher.proHandelUuid, amount, order.name);

                        voucher.redeemedAmount = (voucher.redeemedAmount || 0) + amount;
                        if (voucher.redeemedAmount >= voucher.value) {
                            voucher.status = 'redeemed';
                        } else {
                            voucher.status = 'partial';
                        }
                        await voucher.save();
                        console.log(`✅ Synced Redemption: Descreased PH Voucher ${voucher.proHandelNumber} by ${amount}`);
                    } catch (phErr) {
                        console.error("Failed to sync redemption to ProHandel:", phErr.message);
                    }
                } else {
                    console.log(`⚠️ Shopify Gift Card ${shopifyGiftCardId} used, but not found in our DB. Skipping PH sync.`);
                }
            }
        }

    } catch (error) {
        console.error("Error processing redemptions:", error);
    }
}
